name: Labels Check
on:
  pull_request:
    types: [opened, labeled, unlabeled, synchronize]
jobs:
  QA-check:
    if: github.base_ref == 'develop'
    runs-on: ubuntu-latest
    steps:
      - uses: danielchabr/pr-labels-checker
        id: checkLabel
        with:
          hasSome: QA:tested,QA:skipped
  Do_not_merge-check:
    if: github.base_ref == 'develop'
    runs-on: ubuntu-latest
    steps:
      - uses: danielchabr/pr-labels-checker
        id: checkLabel
        with:
          hasNone: do not merge,blocked
